module.exports = {
	env: {
		es2021: true
	},
	extends: ['eslint:recommended'],
	parserOptions: {
		ecmaVersion: 12,
		sourceType: 'module'
	},
	plugins: ['import'],
	rules: {
		'arrow-body-style': [2, 'as-needed'],
		'arrow-parens': [2, 'as-needed'],
		'arrow-spacing': 2,
		'block-spacing': [2, 'always'],
		'brace-style': [2, '1tbs', { allowSingleLine: true }],
		'camelcase': 2,
		'comma-dangle': [2, 'never'],
		'comma-spacing': [2, { after: true, before: false }],
		'comma-style': [2, 'last'],
		'consistent-return': 2,
		'eqeqeq': [2, 'always'],
		'eol-last': 2,
		'func-call-spacing': [2, 'never'],
		'import/no-unresolved': [2, { commonjs: true }],
		'indent': [2, 'tab'],
		'key-spacing': [2, { afterColon: true, beforeColon: false, mode: 'minimum' }],
		'keyword-spacing': [2, { after: true, before: true, overrides: { function: { after: false }}}],
		'linebreak-style': [2, 'unix'],
		'max-len': [2, { code: 160, ignoreUrls: true }],
		'max-nested-callbacks': [2, { max: 5 }],
		'new-cap': [2, { capIsNew: true, newIsCap: true, properties: true }],
		'new-parens': 2,
		'no-confusing-arrow': [2, { allowParens: true }],
		'no-console': 1,
		'no-constant-condition': [2, { 'checkLoops': false }],
		'no-extra-parens': [2, 'all', { enforceForArrowConditionals: false, nestedBinaryExpressions: false, returnAssign: false }],
		'no-lonely-if': 2,
		'no-loop-func': 2,
		'no-return-assign': 2,
		'no-return-await': 2,
		'no-self-compare': 2,
		'no-shadow-restricted-names': 2,
		'no-trailing-spaces': 2,
		'no-unmodified-loop-condition': 2,
		'no-unneeded-ternary': 2,
		'no-use-before-define': [2, { functions: false }],
		'no-useless-computed-key': 2,
		'no-useless-concat': 2,
		'no-useless-rename': 2,
		'no-var': 2,
		'no-whitespace-before-property': 2,
		'object-curly-spacing': [2, 'always'],
		'object-shorthand': [2, 'always'],
		'operator-assignment': [2, 'always'],
		'operator-linebreak': [2, 'after'],
		'prefer-arrow-callback': 2,
		'prefer-const': 2,
		'prefer-numeric-literals': 2,
		'prefer-rest-params': 2,
		'prefer-spread': 2,
		'quotes': [2, 'double', { allowTemplateLiterals: true }],
		'rest-spread-spacing': [2, 'never'],
		'semi': [2, 'always'],
		'semi-spacing': [2, { after: true, before: false }],
		'sort-imports': 1,
		'sort-vars': 1,
		'space-before-blocks': [2, 'always'],
		'space-before-function-paren': [2, { anonymous: 'never', asyncArrow: 'always', named: 'never' }],
		'space-in-parens': [2, 'never'],
		'space-infix-ops': 2,
		'space-unary-ops': [2, { nonwords: false, overrides: { typeof: false }, words: true }],
		'strict': [2, 'global'],
		'template-curly-spacing': [2, 'never']
	}
};
